## Action Learning 2

- Multiply Two csc_matrix Matrices

## Example 1: Multiply Two csc_matrix Matrices
In this example two sparse matrices are created using csc_matrix() class. These matrices are then multiplied element-wise using multiply() method which performs efficient operations on only the non-zero elements.

In [1]:
import numpy as np
from scipy.sparse import csc_matrix

In [2]:
# Create first csc matrix A
row_A = np.array([0, 0, 1, 2])
col_A = np.array([0, 1, 0, 1])
data_A = np.array([4, 3, 8, 9])
csc_A = csc_matrix((data_A, (row_A, col_A)), shape=(3, 3))

print("First CSC Matrix:\n", csc_A.toarray())

First CSC Matrix:
 [[4 3 0]
 [8 0 0]
 [0 9 0]]


In [3]:
# Create second csc matrix B
row_B = np.array([0, 1, 1, 2])
col_B = np.array([0, 0, 1, 0])
data_B = np.array([7, 2, 5, 1])
csc_B = csc_matrix((data_B, (row_B, col_B)), shape=(3, 3))

print("Second CSC Matrix:\n", csc_B.toarray())

Second CSC Matrix:
 [[7 0 0]
 [2 5 0]
 [1 0 0]]


In [4]:
# Element-wise multiplication
result = csc_A.multiply(csc_B)
print("Element-wise Multiplication Result:\n", result.toarray())

Element-wise Multiplication Result:
 [[28  0  0]
 [16  0  0]
 [ 0  0  0]]
